###############################################
# ███╗░░░███╗░█████╗░██████╗░████████╗██╗░░░██╗
# ████╗░████║██╔══██╗██╔══██╗╚══██╔══╝╚██╗░██╔╝
# ██╔████╔██║███████║██████╔╝░░░██║░░░░╚████╔╝░
# ██║╚██╔╝██║██╔══██║██╔══██╗░░░██║░░░░░╚██╔╝░░
# ██║░╚═╝░██║██║░░██║██║░░██║░░░██║░░░░░░██║░░░
# ╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░░░░╚═╝░░░
###############################################

# Shell Prompt Configuration
# Configuration reference: https://starship.rs/config/

format = "$all"
right_format = "$cmd_duration"
add_newline = true
continuation_prompt = "[➜➜](bold #bd93f9)"

[battery]
charging_symbol = ""
discharging_symbol = ""
[[battery.display]]
threshold = 10
style = "bold #ff5555"

[character]
success_symbol = "[➜](bold #bd93f9)"
error_symbol = "[✗](bold #ff5555)"

[cmd_duration]
format = "[ $duration]($style)"
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"
read_only = ""
read_only_style = "#ff5555"
home_symbol = "~"

[git_branch]
format = " [$symbol(:$remote_branch)]($style)"
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[line_break]
disabled = true

[package]
disabled = true

[python]
symbol = " "

