# Shell Prompt Configuration
# Configuration reference: https://starship.rs/config/

# Show modules on right
right_format = """$cmd_duration"""

# Inserts a blank line between shell prompts
add_newline = true

##Advanced Configuration/Might break with updates
# PS2 Prompt
continuation_prompt = "[➜➜](bold blue)"

[cmd_duration]
format = "[ $duration]($style)"

# Make prompt single line instead of two
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold blue)"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
symbol = " "

[git_branch]
format = " [$symbol(:$remote_branch)]($style)"
